try{
    console.log("Start of Try");

    error;

    console.log("End of Try");
}catch{
    console.log("Error has occured");
}